#!/bin/bash
# PreToolUse (Edit|Write): refuse edits to files generated by render.py; they
# are overwritten on the next render. Point at the template instead.
file=$(jq -r '.tool_input.file_path // empty')
[ -n "$file" ] && [ -f "$file" ] || exit 0

header=$(head -n 3 "$file")
case $header in
    *"Generated by render.py from templates/"*) ;;
    *) exit 0 ;;
esac

template=$(sed -n 's/.*Generated by render.py from \(templates\/[^ ]*\) and.*/\1/p' <<<"$header")
echo "$file is generated by render.py. Edit $template or config.toml instead;" \
    "the PostToolUse hook re-renders and checks the output." >&2
exit 2
