# syntax=docker/dockerfile:1
# Generated by render.py from templates/Containerfile.j2 and config.toml. Do not edit.
FROM debian:trixie

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ARG DEBIAN_FRONTEND=noninteractive

# Base system. build-essential/procps/curl/file/git are what the dotfiles'
# Debian bootstrap needs for Homebrew; util-linux(-extra) provides lscpu,
# which the chezmoi config template calls.
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      build-essential \
      ca-certificates \
      curl \
      file \
      git \
      gnupg \
      less \
      locales \
      ncurses-term \
      openssh-client \
      procps \
      rsync \
      sudo \
      unzip \
      util-linux \
      util-linux-extra \
      wget \
      xz-utils \
      zsh \
 && sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen \
 && locale-gen \
 && rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

# Apple's container leaves no marker such as /.dockerenv; follow the systemd
# convention so tools (e.g. the dotfiles' Claude sandbox settings) can tell
# they run in a container.
ENV container=apple

# Also trust the host's known_hosts, which devbox mounts read-only. ssh keeps
# adding new hosts to the container's own ~/.ssh/known_hosts.
RUN echo 'GlobalKnownHostsFile /etc/ssh/ssh_known_hosts /etc/ssh/ssh_known_hosts2 /run/host-ssh/known_hosts' \
      > /etc/ssh/ssh_config.d/host-known-hosts.conf

# GitHub CLI from the official apt repository.
RUN install -d -m 0755 /etc/apt/keyrings \
 && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
      -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \
 && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
      > /etc/apt/sources.list.d/github-cli.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends gh \
 && rm -rf /var/lib/apt/lists/*

# Docker Engine for `devbox --docker`; dockerd is started by the entrypoint.
RUN curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
 && chmod go+r /etc/apt/keyrings/docker.asc \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
      > /etc/apt/sources.list.d/docker.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
      containerd.io \
      docker-buildx-plugin \
      docker-ce \
      docker-ce-cli \
      docker-compose-plugin \
      iptables \
 && rm -rf /var/lib/apt/lists/*

# chezmoi, system-wide so it is available before the home directory exists.
RUN sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin

# Unprivileged user matching the macOS host uid/gid. Homebrew refuses to run
# as root, and the dotfiles bootstrap calls `sudo apt-get`.
RUN groupadd --non-unique --gid 20 thom \
 && useradd --uid 501 --gid 20 --shell /usr/bin/zsh \
      --home-dir /home/thom --create-home thom \
 && echo 'thom ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/thom \
 && chmod 0440 /etc/sudoers.d/thom \
 && usermod -aG docker thom \
 && install -d -o 501 -g 20 /project

USER thom
WORKDIR /home/thom
ENV PATH=/home/thom/.local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH

ENV HOMEBREW_NO_ANALYTICS=1 \
    HOMEBREW_NO_AUTO_UPDATE=1 \
    HOMEBREW_NO_ENV_HINTS=1 \
    HOMEBREW_NO_INSTALL_CLEANUP=1

# Homebrew and the dotfiles' brew packages in their own layer, so the slow
# (on arm64 Linux largely from-source) install is only redone when the package
# list changes. BuildKit caches `ADD <url>` by content checksum, so this layer
# is invalidated by edits to the data file, not by other dotfiles commits.
RUN NONINTERACTIVE=1 bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
 && brew --version
ADD --chown=501:20 https://raw.githubusercontent.com/thomwiggers/chezmoi-dotfiles/main/.chezmoidata.toml /tmp/chezmoidata.toml
RUN mapfile -t formulae < <(awk '/^brew = \[/ {f=1; next} f && /^\]/ {f=0} f' /tmp/chezmoidata.toml | tr -d ' ",') \
 && echo "installing: ${formulae[*]}" \
 && brew install --formula "${formulae[@]}" \
 && rm -rf "$(brew --cache)" /tmp/chezmoidata.toml

# Dotfiles without the age key: `--exclude encrypted` (space-separated, as the
# dotfiles' decrypt script greps for it) skips the passphrase prompt.
# Its Homebrew bootstrap finds everything above already installed.
# DOTFILES_REV busts the cache when the dotfiles repository changes.
ARG DOTFILES_REV=unknown
RUN echo "dotfiles rev: ${DOTFILES_REV}" \
 && chezmoi init --apply --exclude encrypted https://github.com/thomwiggers/chezmoi-dotfiles.git \
 && rm -rf "$(brew --cache)"

# Claude Code, native installer. CLAUDE_CACHE_BUST lets CI pick up new
# releases without rebuilding the (slow) dotfiles layer.
ARG CLAUDE_CACHE_BUST=unknown
RUN echo "claude cache bust: ${CLAUDE_CACHE_BUST}" \
 && curl -fsSL https://claude.ai/install.sh | bash \
 && claude --version

# Snapshot the home directory. The real home is a persistent host mount; the
# entrypoint seeds it from this copy on first start.
USER root
ARG IMAGE_ID=unknown
RUN cp -a /home/thom /opt/home-seed \
 && echo "${IMAGE_ID}" > /opt/home-seed/.thom-container-image \
 && chown 501:20 /opt/home-seed/.thom-container-image

COPY --chmod=0755 entrypoint.sh /usr/local/bin/entrypoint

WORKDIR /project
ENTRYPOINT ["/usr/local/bin/entrypoint"]
CMD ["/usr/bin/zsh", "-l"]
