#!/bin/zsh -f
# Generated by render.py from templates/install.sh.j2 and config.toml. Do not edit.
#
# Install the devbox launcher on macOS. From a clone, `./install.sh` symlinks
# bin/devbox (so `git pull` updates it); otherwise it downloads it:
#
#   curl -fsSL https://raw.githubusercontent.com/thomwiggers/thom-container/main/install.sh | zsh
#
# zsh because it is what macOS ships; -f skips rc files.
setopt err_exit no_unset pipe_fail

bin_dir=${THOM_CONTAINER_BIN_DIR:-$HOME/.local/bin}
state_root="$HOME/.cache/thom-containers"
key_dir="$HOME/.config/chezmoi"
image=ghcr.io/thomwiggers/thom-container:latest
pull=1

usage() {
    cat <<EOF
Usage: install.sh [--no-pull]

Installs devbox into $bin_dir [env: THOM_CONTAINER_BIN_DIR], starts the
container system service and pulls $image.

Options:
      --no-pull   Don't pull the image
  -h, --help      Show this help
EOF
}

while [ $# -gt 0 ]; do
    case $1 in
        --no-pull) pull= ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "install.sh: unknown option: $1" >&2
            exit 1
            ;;
    esac
    shift
done

step() { printf '==> %s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }

[ "$(uname -s)" = Darwin ] || warn "devbox is meant for macOS with Apple's container"
[ "$(uname -m)" = arm64 ] || warn "the image is built for arm64 (Apple silicon) only"

if ! command -v container >/dev/null 2>&1; then
    echo "Apple's 'container' CLI is not installed." >&2
    echo "Get the installer from https://github.com/apple/container/releases and rerun." >&2
    exit 1
fi

step "Installing devbox into $bin_dir"
mkdir -p "$bin_dir"
# Run as a file ($0 is this script) or piped into zsh ($0 is "zsh").
src_dir=
if [[ ${0:t} == install.sh && -f $0 ]]; then
    src_dir=${0:A:h}
fi
if [[ -n $src_dir && -x $src_dir/bin/devbox ]]; then
    ln -sfn "$src_dir/bin/devbox" "$bin_dir/devbox"
    echo "    symlinked to $src_dir/bin/devbox"
else
    tmp=$(mktemp)
    trap 'rm -f "$tmp"' EXIT
    curl -fsSL "https://raw.githubusercontent.com/thomwiggers/thom-container/main/bin/devbox" -o "$tmp"
    install -m 0755 "$tmp" "$bin_dir/devbox"
    echo "    downloaded from https://raw.githubusercontent.com/thomwiggers/thom-container/main/bin/devbox"
fi

case ":$PATH:" in
    *":$bin_dir:"*) ;;
    *) warn "$bin_dir is not on your PATH" ;;
esac

step "Creating persistent homes in $state_root"
mkdir -p "$state_root/private"
mkdir -p "$state_root/work"

if [ ! -f "$key_dir/key.txt" ]; then
    warn "no age key at $key_dir/key.txt; encrypted dotfiles will stay locked"
fi

step "Starting the container system service"
# Explicit kernel flag: with `curl | zsh`, a prompt would eat the script.
container system status >/dev/null 2>&1 || container system start --enable-kernel-install

if [ -n "$pull" ]; then
    step "Pulling $image"
    if ! container image pull "$image"; then
        echo "Pull failed. If the package is private, run:" >&2
        echo "    container registry login ghcr.io" >&2
        exit 1
    fi
fi

step "Done. Run 'devbox' in a project folder."
