#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["jinja2>=3.1"]
# ///
"""Render the Containerfile, entrypoint and launcher from config.toml."""

import argparse
import sys
import tomllib
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

ROOT = Path(__file__).resolve().parent

# template name -> (output path, executable)
OUTPUTS = {
    "Containerfile.j2": ("Containerfile", False),
    "entrypoint.sh.j2": ("entrypoint.sh", True),
    "devbox.j2": ("bin/devbox", True),
}


def render(config: dict) -> dict[Path, tuple[str, bool]]:
    env = Environment(
        loader=FileSystemLoader(ROOT / "templates"),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    header = "Generated by render.py from templates/{} and config.toml. Do not edit."
    rendered = {}
    for template, (output, executable) in OUTPUTS.items():
        text = env.get_template(template).render(
            **config, generated_header=header.format(template)
        )
        rendered[ROOT / output] = (text, executable)
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any generated file is out of date",
    )
    args = parser.parse_args()

    with (ROOT / "config.toml").open("rb") as f:
        config = tomllib.load(f)

    if config["host"]["default_profile"] not in config["host"]["profiles"]:
        print("config: host.default_profile must be in host.profiles", file=sys.stderr)
        return 1

    stale = []
    for path, (text, executable) in render(config).items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            if executable:
                path.chmod(0o755)

    for path in stale:
        print(f"{'stale' if args.check else 'wrote'}: {path}")
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    sys.exit(main())
